/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectInterface;
import projectClasses.Administrator;
import projectClasses.Processor;
import auxClasses.Hilo;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author juanmendezl
 */
public class Init extends javax.swing.JFrame {
    private Administrator admin;
    private final Hilo hilo;

    /**
     * Creates new form Init
     */
    public Init() {
        initComponents();
        admin = new Administrator(new Processor(10));
        hilo = new Hilo(admin.getProcessor().getDuration(),admin, admin.getProcessor(), this,  this.winnersL, this.winnersR,
                this.statusField1, this.statusField2,
        this.leftHighQ, this.leftMidQ, this.leftLowQ, this.leftAuxQ, this.rightHighQ, this.rightMidQ, this.rightLowQ, this.rightAuxQ, this.jSpinner1);
        hilo.start();
        
    }
    
    public void updateFighterImages() {
        if (admin.getActiveFighterL() != null && admin.getActiveFighterR() != null) {
            String fighterLName = admin.getActiveFighterL().getName();
            String fighterRName = admin.getActiveFighterR().getName();
            int fighterLId = admin.getActiveFighterL().getId();
            int fighterRId = admin.getActiveFighterR().getId();

            SwingUtilities.invokeLater(() -> {
                admin.setIconForLabel(jLabel4, fighterLName); // Use Administrator to set the icon
                admin.setIconForLabel(jLabel3, fighterRName);
                nameL.setText(fighterLName);
                nameR.setText(fighterRName);
                idL.setText(String.valueOf(fighterLId));
                idR.setText(String.valueOf(fighterRId));
            });
        }
    }
    
   /* private void updateLabels(Administrator admin){
        
        if (admin.getActiveFighterL() != null && admin.getActiveFighterR() != null){
            String fighterLName = admin.getActiveFighterL().getName();
            String fighterRName = admin.getActiveFighterR().getName();
        
        
        
            setIconForLabel(jLabel4, fighterLName);
            setIconForLabel(jLabel3, fighterRName);
        }
    }
    
    private void setIconForLabel(javax.swing.JLabel label, String fighterName){
        String imagePath = "/projectInterface.fighters/" + fighterName.toLowerCase() + ".png";
        URL imageUrl = getClass().getResource(imagePath);
        
        if (imageUrl != null){
            ImageIcon icon = new ImageIcon(imageUrl);
            label.setIcon(icon);
        } else {
            label.setText("Imagen no encontrada: " + fighterName);
            label.setIcon(null);
        }
    } */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        FightingTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FightingTitle2 = new javax.swing.JLabel();
        FightingTitle3 = new javax.swing.JLabel();
        FightingTitle4 = new javax.swing.JLabel();
        FightingTitle5 = new javax.swing.JLabel();
        FightingTitle6 = new javax.swing.JLabel();
        FightingTitle7 = new javax.swing.JLabel();
        FightingTitle8 = new javax.swing.JLabel();
        FightingTitle9 = new javax.swing.JLabel();
        FightingTitle10 = new javax.swing.JLabel();
        FightingTitle11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rightHighQ = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        leftMidQ = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        rightMidQ = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        rightLowQ = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        leftHighQ = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        rightAuxQ = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        leftLowQ = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        leftAuxQ = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FightingTitle12 = new javax.swing.JLabel();
        FightingTitle13 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        winnersR = new javax.swing.JTextField();
        winnersL = new javax.swing.JTextField();
        nameR = new javax.swing.JTextField();
        nameL = new javax.swing.JTextField();
        idL = new javax.swing.JTextField();
        idR = new javax.swing.JTextField();
        FightingTitle14 = new javax.swing.JLabel();
        FightingTitle15 = new javax.swing.JLabel();
        statusField2 = new javax.swing.JTextField();
        statusField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, -1, -1));

        FightingTitle.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        FightingTitle.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle.setText("VICTORIAS:");
        jPanel1.add(FightingTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectInterface/Untitled design.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectInterface/output-onlinepngtools (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        FightingTitle2.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        FightingTitle2.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle2.setText("BATTLE FIELD");
        jPanel1.add(FightingTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 150, 40));

        FightingTitle3.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        FightingTitle3.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle3.setText("COLA DE PRIORIDAD 1:");
        jPanel1.add(FightingTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 150, 30));

        FightingTitle4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        FightingTitle4.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle4.setText("V.");
        jPanel1.add(FightingTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 30, 30));

        FightingTitle5.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        FightingTitle5.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle5.setText("COLA DE PRIORIDAD 2:");
        jPanel1.add(FightingTitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 150, 30));

        FightingTitle6.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        FightingTitle6.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle6.setText("ID:");
        jPanel1.add(FightingTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 30, 30));

        FightingTitle7.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        FightingTitle7.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle7.setText("COLA DE PRIORIDAD 3:");
        jPanel1.add(FightingTitle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 150, 30));

        FightingTitle8.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        FightingTitle8.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle8.setText("COLA DE PRIORIDAD 2:");
        jPanel1.add(FightingTitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 150, 30));

        FightingTitle9.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        FightingTitle9.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle9.setText("COLA DE REFUERZOS");
        jPanel1.add(FightingTitle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 150, 30));

        FightingTitle10.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        FightingTitle10.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle10.setText("COLA DE PRIORIDAD 3:");
        jPanel1.add(FightingTitle10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 150, 30));

        FightingTitle11.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        FightingTitle11.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle11.setText("COLA DE REFUERZOS");
        jPanel1.add(FightingTitle11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, 30));

        rightHighQ.setColumns(20);
        rightHighQ.setRows(5);
        jScrollPane1.setViewportView(rightHighQ);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 140, 50));

        leftMidQ.setColumns(20);
        leftMidQ.setRows(5);
        jScrollPane2.setViewportView(leftMidQ);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 140, 50));

        rightMidQ.setColumns(20);
        rightMidQ.setRows(5);
        jScrollPane4.setViewportView(rightMidQ);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 140, 50));

        rightLowQ.setColumns(20);
        rightLowQ.setRows(5);
        jScrollPane5.setViewportView(rightLowQ);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 140, 50));

        leftHighQ.setColumns(20);
        leftHighQ.setRows(5);
        jScrollPane6.setViewportView(leftHighQ);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 140, 50));

        rightAuxQ.setColumns(20);
        rightAuxQ.setRows(5);
        jScrollPane7.setViewportView(rightAuxQ);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 140, 50));

        leftLowQ.setColumns(20);
        leftLowQ.setRows(5);
        jScrollPane8.setViewportView(leftLowQ);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 140, 50));

        leftAuxQ.setColumns(20);
        leftAuxQ.setRows(5);
        jScrollPane9.setViewportView(leftAuxQ);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 140, 50));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 220, 230));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 220, 230));

        FightingTitle12.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        FightingTitle12.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle12.setText("VELOCIDAD");
        jPanel1.add(FightingTitle12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 100, 30));

        FightingTitle13.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        FightingTitle13.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle13.setText("VICTORIAS:");
        jPanel1.add(FightingTitle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 80, 30));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(10, 1, 20, 1));
        jSpinner1.setToolTipText("");
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        winnersR.setEditable(false);
        winnersR.setColumns(3);
        winnersR.setText("0");
        winnersR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winnersRActionPerformed(evt);
            }
        });
        jPanel1.add(winnersR, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        winnersL.setEditable(false);
        winnersL.setColumns(3);
        winnersL.setText("0");
        winnersL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winnersLActionPerformed(evt);
            }
        });
        jPanel1.add(winnersL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        nameR.setEditable(false);
        nameR.setColumns(15);
        nameR.setText("choosing");
        jPanel1.add(nameR, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        nameL.setEditable(false);
        nameL.setColumns(15);
        nameL.setText("choosing");
        nameL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameLActionPerformed(evt);
            }
        });
        jPanel1.add(nameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        idL.setEditable(false);
        idL.setColumns(3);
        idL.setText("0");
        idL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idLActionPerformed(evt);
            }
        });
        jPanel1.add(idL, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        idR.setEditable(false);
        idR.setColumns(3);
        idR.setText("0");
        jPanel1.add(idR, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        FightingTitle14.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        FightingTitle14.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle14.setText("COLA DE PRIORIDAD 1:");
        jPanel1.add(FightingTitle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 30));

        FightingTitle15.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        FightingTitle15.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle15.setText("ID:");
        jPanel1.add(FightingTitle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 30, 30));

        statusField2.setColumns(10);
        statusField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusField2ActionPerformed(evt);
            }
        });
        jPanel1.add(statusField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        statusField1.setColumns(10);
        statusField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusField1ActionPerformed(evt);
            }
        });
        jPanel1.add(statusField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void winnersLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winnersLActionPerformed
        // TODO add your handling code here:
        winnersL.setText("0");
    }//GEN-LAST:event_winnersLActionPerformed

    private void winnersRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winnersRActionPerformed
        // TODO add your handling code here:
        winnersR.setText("0");
    }//GEN-LAST:event_winnersRActionPerformed

    private void nameLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameLActionPerformed

    private void idLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idLActionPerformed

    private void statusField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusField2ActionPerformed

    private void statusField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Init().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FightingTitle;
    private javax.swing.JLabel FightingTitle10;
    private javax.swing.JLabel FightingTitle11;
    private javax.swing.JLabel FightingTitle12;
    private javax.swing.JLabel FightingTitle13;
    private javax.swing.JLabel FightingTitle14;
    private javax.swing.JLabel FightingTitle15;
    private javax.swing.JLabel FightingTitle2;
    private javax.swing.JLabel FightingTitle3;
    private javax.swing.JLabel FightingTitle4;
    private javax.swing.JLabel FightingTitle5;
    private javax.swing.JLabel FightingTitle6;
    private javax.swing.JLabel FightingTitle7;
    private javax.swing.JLabel FightingTitle8;
    private javax.swing.JLabel FightingTitle9;
    private javax.swing.JTextField idL;
    private javax.swing.JTextField idR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea leftAuxQ;
    private javax.swing.JTextArea leftHighQ;
    private javax.swing.JTextArea leftLowQ;
    private javax.swing.JTextArea leftMidQ;
    private javax.swing.JTextField nameL;
    private javax.swing.JTextField nameR;
    private javax.swing.JTextArea rightAuxQ;
    private javax.swing.JTextArea rightHighQ;
    private javax.swing.JTextArea rightLowQ;
    private javax.swing.JTextArea rightMidQ;
    private javax.swing.JButton salir;
    private javax.swing.JTextField statusField1;
    private javax.swing.JTextField statusField2;
    private javax.swing.JTextField winnersL;
    private javax.swing.JTextField winnersR;
    // End of variables declaration//GEN-END:variables
}
